# Describes tests that we either:
#   - Outright skip.
#   - Run and alert owners on failure.
# To outright skip a test add a "skip: true" property.
# Only do this for tests that are currently expected to fail constantly and the noise is unbearable!
# Otherwise, tests must have owner(s). Owners are identified by their Slack id, (profile, three dots, copy member id).
# If there is no owner for failed test the build will fail, regardless of if it matches in this file.
# When a failing test matches one or more of the "regex" properties below,
# a message is sent to slack channel #aztec3-ci tagging the owners.
# If an optional error_regex is provided, the output file must match for the test to be considered a flake.

names:
  - adam: &adam "U04BM8H25NJ"
  - akosh: &akosh "U07PQ3Y4GHJ"
  - alex: &alex "U05QWV669JB"
  - charlie: &charlie "UKUMA5J7K"
  - david: &david "U03T2QRT1NW"
  - grego: &grego "U0689QRCE9L"
  - lasse: &lasse "U03E5SYLY3Z"
  - leila: &leila "UBLTU1NJ3"
  - luke: &luke "U03JYU7AQET"
  - mitch: &mitch "U06AY5G1NRK"
  - palla: &palla "U04TPBU26E8"
  - phil: &phil "U02G4KAD57Y"
  - sean: &sean "U04DT239VQU"
  - tom: &tom "U04LLT331NK"
  - sergei: &sergei "U05RR81391B"
  - spyros: &spyros "U03FCET0DQE"
  - jan: &jan "U03FGA0BWNR"
  - esau: &esau "U067FJ9A4Q1"
  - saleel: &saleel "U07KJ0AV20J"
  - nico: &nico "U06D2QSLY10"
  - lucas: &lucas "U05MW7WQ8LQ"
  - suyash: &suyash "U08QFSL6LPM"

tests:
  # barretenberg
  #
  # Rare. But I saw it happen twice in 10 CI runs. Then twice in 10000 mainframe runs. Today I can't reproduce.
  # Grind with: seq 1 10000 | parallel --bar "barretenberg/cpp/scripts/run_test.sh join_split_example_tests join_split_tests.test_defi_deposit_second_bridge_output_in_use_and_same_virtual_bridge_output_asset_ids >/dev/null"
  # Logic failed: field_t::range_constraint
  # /home/aztec-dev/aztec-packages/barretenberg/cpp/src/barretenberg/examples/join_split/join_split.test.cpp:1735: Failure
  # Value of: result.valid
  #   Actual: false
  # Expected: true
  - regex: "join_split_example_tests"
    error_regex: "field_t::range_constraint"
    owners:
      - *luke
  - regex: "barretenberg/acir_tests/scripts/browser_prove.sh"
    error_regex: "Failed to fetch"
    owners:
      - *adam
  - regex: "barretenberg/acir_tests/scripts/browser_prove.sh"
    error_regex: "RuntimeError: Out of bounds memory access"
    owners:
      - *adam
  - regex: "barretenberg/acir_tests/scripts/browser_prove.sh"
    error_regex: "call_indirect to a null table entry"
    owners:
      - *adam
  - regex: "barretenberg/acir_tests/scripts/browser_prove.sh"
    error_regex: "Input is not large enough"
    owners:
      - *adam
  # https://gist.github.com/spalladino/4fd3d2abd7b7fb05be2e556649868626
  - regex: "barretenberg/acir_tests/scripts/browser_prove.sh"
    error_regex: "sending signal TERM to command"
    owners:
      - *adam
  - regex: "barretenberg/cpp/scripts/run_bench.sh wasm bb-micro-bench/wasm/ultra_honk"
    error_regex: "Aborted.*core dumped"
    owners:
      - *adam

  # /home/aztec-dev/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_edge_cases.test.cpp:142: Failure
  # Expected equality of these values:
  #   combined_a.get_value() > fq_ct::modulus
  #     Which is: false
  #   true
  # http://ci.aztec-labs.com/9cb61bfe05d4f32f
  - regex: "stdlib_primitives_tests stdlib_bigfield_edge_cases/2.reduction_check_works"
    error_regex: "combined_a.get_value() > fq_ct::modulus"
    owners:
      - *suyash

  # noir
  # Something to do with how I run the tests now. Think these are fine in nextest.
  - regex: "noir_lsp-.* notifications::notification_tests::test_caches_open_files"
    skip: true
    owners:
      - *charlie
  - regex: "noir_lsp-.* requests::"
    skip: true
    owners:
      - *charlie
  # Sometimes see this on ARM. But not when run on it's own...
  - regex: "tests::debug_ram_blowup_regression"
    skip: true
    owners:
      - *charlie

  # AD: hit this flake
  # 18:04:38 thread 'arb_program_freqs_in_expected_range' panicked at tooling/ast_fuzzer/tests/calibration.rs:75:5:
  # 18:04:38 Brillig loops: 11
  # 18:04:38 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  - regex: "noir/scripts/run_test.sh calibration.* arb_program_freqs_in_expected_range"
    error_regex: "panicked at tooling/ast_fuzzer/tests/calibration.rs"
    owners:
      - *tom

  # e2e tests skipped
  - regex: "testbench/port_change.test.ts"
    skip: true
    owners:
      - *sean
  # e2e tests flakes
  - regex: "src/e2e_p2p"
    error_regex: "could not listen on any available address"
    owners:
      - *sean
  - regex: "src/e2e_p2p/reex"
    error_regex: "Received promise resolved instead of rejected"
    owners:
      - *sean
  - regex: "src/e2e_p2p/reex"
    error_regex: "FormattedViemError: Nonce provided for the transaction is lower than the current nonce of the account."
    owners:
      - *sean
  # http://ci.aztec-labs.com/5a291189b35a1b38
  # http://ci.aztec-labs.com/b175321d1289021c
  - regex: "src/e2e_p2p"
    error_regex: 'CodeError: writable end state is "writing" not "ready"'
    owners:
      - *palla
  - regex: "src/e2e_p2p/reqresp"
    owners:
      - *palla
  - regex: "src/e2e_p2p"
    error_regex: "TimeoutError: Timeout awaiting blocks mined"
    owners:
      - *palla
  - regex: "src/e2e_p2p"
    error_regex: "TimeoutError: Timeout awaiting isMined"
    owners:
      - *palla
  - regex: "src/e2e_p2p/gossip_network"
    error_regex: "TimeoutError: Timeout awaiting isMined"
    owners:
      - *palla
  - regex: "e2e_p2p/validators_sentinel"
    error_regex: "Received: 49999999999999999999n"
    owners:
      - *mitch
  - regex: "e2e_p2p/validators_sentinel"
    error_regex: "Expected: >= 2"
    owners:
      - *palla
  - regex: "e2e_p2p/validators_sentinel"
    error_regex: "ContractFunctionExecutionError.*execution failed"
    owners:
      - *palla
  - regex: "src/e2e_p2p/preferred_gossip_network.test.ts"
    owners:
      - *palla
  - regex: "src/e2e_p2p/gossip_network.test.ts"
    error_regex: "Block 5 not yet synced"
    owners:
      - *palla
  - regex: "src/e2e_fees/private_payments"
    owners:
      - *phil
  - regex: "src/e2e_token_contract/access_control"
    error_regex: "HttpRequestError: HTTP request failed."
    owners:
      - *charlie
  - regex: "src/e2e_lending_contract"
    error_regex: "✕ Depositing"
    owners:
      - *lasse
  - regex: "src/e2e_lending_contract"
    error_regex: "✕ Repay"
    owners:
      - *lasse
  # http://ci.aztec-labs.com/d681011c15fccdfe
  # simulator:avm(f:0x9756f620) Unknown error thrown by AVM during bytecode retrieval: AssertionError [ERR_ASSERTION]: Contract instance for address 0x0f48856620f39f6ae1da55786b7e93e2358081333605161af4e29cfd507a3039 in DB: false != nullifier tree: true. This is a bug!
  - regex: "src/e2e_epochs/epochs_proof_public_cross_chain.test.ts"
    error_regex: "This is a bug"
    owners:
      - *palla
  - regex: "src/e2e_epochs/epochs_proof_public_cross_chain.test.ts"
    error_regex: "Error: Failed to find an available publisher"
    owners:
      - *palla
  - regex: "src/e2e_epochs/epochs_l1_reorgs.test.ts"
    owners:
      - *palla
  # http://ci.aztec-labs.com/e85ff6c5da65a1e7
  - regex: "src/e2e_cross_chain_messaging/l1_to_l2.test.ts"
    error_regex: "Failed to advance block"
    owners:
      - *palla
  - regex: "src/e2e_epochs/epochs_empty_blocks"
    error_regex: "✕ successfully proves multiple epochs"
    owners:
      - *lasse
  - regex: "src/e2e_cross_chain_messaging/token_bridge_private"
    error_regex: "✕ Claim secret is enough to consume the message"
    owners:
      - *lasse
  - regex: "src/e2e_cross_chain_messaging/token_bridge_public"
    error_regex: "✕ Someone else can mint funds to me on my behalf"
    owners:
      - *lasse
  - regex: "src/e2e_cross_chain_messaging/token_bridge_public"
    error_regex: "✕ Publicly deposit funds"
    owners:
      - *lasse
  - regex: "src/e2e_cross_chain_messaging/token_bridge_failure_cases"
    error_regex: "✕ Can't claim funds"
    owners:
      - *lasse
  - regex: "src/e2e_l1_publisher/e2e_l1_publisher.test.ts"
    error_regex: "Anvil failed to stop in time|Cannot read properties of undefined"
    owners:
      - *palla
  # http://ci.aztec-labs.com/f2007345762c50a8
  - regex: "src/e2e_multi_validator_node.test.ts"
    error_regex: "✕ should attest ONLY with the correct validator keys"
    owners:
      - *spyros
  - regex: "src/e2e_epochs/(epochs_simple_block_building|epochs_high_tps_block_building|epochs_first_slot).test.ts"
    error_regex: "Failed events from sequencers"
    owners:
      - *palla
  # http://ci.aztec-labs.com/a1d8b4d360d6d658
  - regex: "src/e2e_epochs/epochs_first_slot.test.ts"
    error_regex: "expect\\(received\\).toContain\\(expected\\)"
    owners:
      - *palla
  # http://ci.aztec-labs.com/3b197577b96c3639
  # http://ci.aztec-labs.com/d429457d95d075e2
  - regex: "src/e2e_p2p/slash_veto_demo.test.ts"
    error_regex: "timeout: sending signal TERM to command|ValidatorSelection__InsufficientValidatorSetSize"
    owners:
      - *palla
  # http://ci.aztec-labs.com/2927032942451013
  - regex: "src/e2e_p2p/valid_epoch_pruned_slash.test.ts"
    error_regex: "Timeout waiting for proposal execution"
    owners:
      - *palla

  # yarn-project tests
  - regex: "p2p/src/services/discv5/discv5_service.test.ts"
    error_regex: "Timeout: Failed to connect to"
    owners:
      - *sean
  - regex: "p2p/src/client/p2p_client.test.ts"
    error_regex: "Exceeded timeout of 120000"
    owners:
      - *sean
  - regex: "p2p/src/services/reqresp/reqresp.test.ts"
    error_regex: "CodeError: writable end state is .writing. not .ready."
    owners:
      - *sean
  - regex: "p2p/src/services/reqresp/reqresp.test.ts"
    error_regex: "✕ should stop after max retry attempts"
    owners:
      - *sean
  - regex: "p2p/src/client/test/p2p_client.integration_message_propagation.test.ts"
    error_regex: "will propagate messages to peers at the same version"
    owners:
      - *palla
  - regex: "p2p/src/client/test/p2p_client.integration_status_handshake.test.ts"
    error_regex: "Expected number of calls"
    owners:
      - *palla
  - regex: "yarn-project/kv-store"
    error_regex: "Could not import your test module"
    owners:
      - *alex
  - regex: "yarn-project/kv-store"
    error_regex: "timeout: sending signal TERM to command"
    owners:
      - *alex
  - regex: "yarn-project/kv-store"
    error_regex: "Failed to fetch dynamically imported module"
    owners:
      - *alex
  - regex: "ethereum/src/test/tx_delayer.test.ts"
    error_regex: "delays a transaction until a given L1 timestamp"
    owners:
      - *esau
  - regex: "ethereum/src/l1_tx_utils.test.ts"
    error_regex: "✕ attempts to cancel timed out blob transactions with correct parameters"
    owners:
      - *palla
  - regex: "ivc-integration/src/rollup_ivc_integration.test.ts"
    error_regex: "Exceeded timeout of"
    owners:
      - *luke
  - regex: "slasher/src/slasher_client.test.ts"
    error_regex: "ContractFunctionExecutionError: The contract function"
    owners:
      - *mitch
  - regex: "e2e_p2p/inactivity_slash_with_consecutive_epochs.test.ts"
    error_regex: "only slashes validator inactive for N consecutive epochs"
    owners:
      - *palla

  # Nightly GKE tests
  - regex: "spartan/bootstrap.sh"
    owners:
      - *alex

  # aztec-up
  - regex: "aztec-up/scripts/run_test.sh"
    error_regex: "Is the docker daemon running"
    owners:
      - *charlie
  - regex: "aztec-up/scripts/run_test.sh amm_flow"
    error_regex: "code: 124"
    owners:
      - *esau
  - regex: "aztec-up/scripts/run_test.sh amm_flow"
    error_regex: "Sumcheck failed"
    owners:
      - *luke

  # boxes
  - regex: "vanilla-all-browsers box boxes"
    error_regex: "Error: Timed out [0-9]+ms waiting for expect\\(locator\\)"
    owners:
      - *saleel

  - regex: "run_compose_test vite-[a-z]* box boxes"
    error_regex: "Test timeout of [0-9]+ms exceeded."
    owners:
      - *saleel

  - regex: "run_compose_test react-[a-z]* box boxes"
    error_regex: "Test timeout of [0-9]+ms exceeded."
    owners:
      - *saleel

  - regex: "run_compose_test react-[a-z]* box boxes"
    error_regex: "toBeVisible" # http://ci.aztec-labs.com/b7b10b95167d5ed6
    owners:
      - *saleel

  - regex: "tests/browser.spec.ts"
    error_regex: "Error: locator\\.click: Test timeout of"
    owners:
      - *saleel

  - regex: "BOX=vanilla BROWSER=* run_compose_test vanilla-all-browsers box boxes" # http://ci.aztec-labs.com/49f9945bc00aeef9
    error_regex: "create account and cast vote"
    owners:
      - *saleel

  - regex: "src/e2e_p2p/inactivity_slash.test.ts"
    error_regex: "Cannot propose.*since the committee does not exist on L1"
    owners:
      - *palla

  # Slack testing.
  - regex: "nonsense to match"
    error_regex: "something else"
    owners:
      - *charlie
      - *adam
