/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn bbapi_free_result(p: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn acir_get_circuit_sizes(
        constraint_system_buf: *const u8,
        has_ipa_claim: *const bool,
        total: *mut u32,
        subgroup: *mut u32,
    );
}
unsafe extern "C" {
    pub fn bbapi_non_chonk(
        input_in: *const u8,
        input_len_in: usize,
        output_out: *mut *mut u8,
        output_len_out: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn bbapi_set_verbose_logging(enabled: bool);
}
unsafe extern "C" {
    pub fn bbapi_set_debug_logging(enabled: bool);
}
unsafe extern "C" {
    pub fn bbapi_init(crs_path: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn bbapi_cleanup();
}
