opentelemetry-collector:
  replicaCount: 1
  resources:
    requests:
      memory: 12Gi
      cpu: "2"
  nodeSelector:
    node-type: infra
    #   pool: spot
    # tolerations:
    #   - key: "cloud.google.com/gke-spot"
    #     operator: "Equal"
    #     value: "true"
    #     effect: "NoSchedule"
  ports:
    jaeger-compact:
      enabled: false
  service:
    enabled: true
    type: LoadBalancer
  config:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 10000
        spike_limit_mib: 2000
      filter/large_histograms:
        metrics:
          datapoint:
            - metric.type == METRIC_DATA_TYPE_HISTOGRAM and Len(explicit_bounds) > 20

      transform/promote_resource_attributes:
        metric_statements:
          - context: datapoint
            statements:
            # see recommendations https://prometheus.io/docs/guides/opentelemetry/#promoting-resource-attributes
            - set(attributes["service.instance.id"], resource.attributes["service.instance.id"])
            - set(attributes["service.name"], resource.attributes["service.name"])
            - set(attributes["service.namespace"], resource.attributes["service.namespace"])
            - set(attributes["k8s.namespace.name"], resource.attributes["k8s.namespace.name"])
            - set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"])
            - set(attributes["region"], resource.attributes["region"])
            - set(attributes["network"], resource.attributes["network"])

      metricstransform:
        transforms:
          - include: 'system.cpu.utilization'
            match_type: strict
            action: combine
            new_name: 'system.cpu.utilization_combined'
            operations:
              - action: aggregate_labels
                label_set: [ system.cpu.state ]
                aggregation_type: mean

    exporters:
      prometheus:
        endpoint: ${env:MY_POD_IP}:8889
        metric_expiration: 5m
        resource_to_telemetry_conversion:
          enabled: false
      otlp/tempo:
        endpoint: http://metrics-tempo.metrics:4317
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - filter/large_histograms
            - metricstransform
            - transform/promote_resource_attributes
            - batch
          exporters:
            - prometheus
            # - debug
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp/tempo

prometheus:
  server:
    resources:
      requests:
        memory: 40Gi
        cpu: "3.5"
    nodeSelector:
      node-type: infra
    #   pool: spot
    # tolerations:
    #   - key: "cloud.google.com/gke-spot"
    #     operator: "Equal"
    #     value: "true"
    #     effect: "NoSchedule"

    persistentVolume:
      enabled: true
      size: 100Gi
    replicaCount: 1
    statefulSet:
      enabled: true
  alertmanager:
    nodeSelector:
      node-type: infra
  nodeExporter:
    nodeSelector:
      node-type: infra
  pushgateway:
    nodeSelector:
      node-type: infra

loki:
  enabled: false

tempo:
  enabled: true
  tempo:
    resources:
      requests:
        memory: 4Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "4"
    retention: 120h
    ingester:
      max_block_bytes: 524288000  # 500MB
      max_block_duration: 30m
    distributor:
      log_received_spans:
        enabled: false
  persistence:
    enabled: true
    size: 256Gi
    storageClassName: standard-rwo
  nodeSelector:
    node-type: infra

# https://artifacthub.io/packages/helm/grafana/grafana
grafana:
  resources:
    requests:
      memory: 4Gi
      cpu: "1.5"
  nodeSelector:
    node-type: infra
  service:
    type: LoadBalancer
  persistence:
    type: statefulset
    storageClassName: standard-rwo
    enabled: true
    size: "10Gi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: spartan-metrics-prometheus
          isDefault: true
          url: http://metrics-prometheus-server.metrics:80
        - name: Tempo
          type: tempo
          url: http://metrics-tempo.metrics:3100
